apiVersion: v1
kind: Service
metadata:
  name: app-alumnos-backend
  namespace: app-alumnos
spec:
  selector:
    app: app-alumnos-backend
  ports:
    - port: 3001
      targetPort: 3001
  type: ClusterIP
