apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-alumnos-backend
  namespace: app-alumnos
spec:
  replicas: 2
  progressDeadlineSeconds: 600
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: app-alumnos-backend
  template:
    metadata:
      labels:
        app: app-alumnos-backend
    spec:
      containers:
        - name: backend
          image: 919889862541.dkr.ecr.us-east-1.amazonaws.com/app-alumnos-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "app-alumnos-db-service"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: app-alumnos-db-secret
                  key: MYSQL_DATABASE
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://$(DB_HOST):$(DB_PORT)/$(DB_NAME)?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-alumnos-db-secret
                  key: MYSQL_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-alumnos-db-secret
                  key: MYSQL_PASSWORD

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /api/alumnos
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5

          livenessProbe:
            httpGet:
              path: /api/alumnos
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 15
            failureThreshold: 3
            timeoutSeconds: 5